### PR TITLE
Add File extension check for .yml

### PR DESCRIPTION
**Pull request by ritwik12**
#48
Not sure if this will work. This is very Naive. Still want to give a thought if while checking for diffs only if we check the extension of file being `.yml` or not.

### CODE REVIEW

**Comment by shiftkey** [comment]
At first glance I think this check will mean it skips the "comment on PR" step when it encounters an invalid data file. I'd love for this to still add a comment to the PR, but just with the helpful context (I don't think this code exists yet, the commit status is there as a fallback).

**Comment by ritwik12** [comment]
@shiftkey Agreed. Sorry I couldn't understand the last line. Also, what message you we post on comment if this happens?

**Comment by shiftkey** [comment]
> Also, what message you we post on comment if this happens?

I don't think anything happens currently. We assume that all changes to data files are valid, which is why we didn't catch the file extension warning.

**Comment by ritwik12** [comment]
@shiftkey Alright. But it will be good to give a warning for file extension also :)

**Comment by shiftkey** [comment]
Let's move this to https://github.com/shiftkey/webhooks/issues/60 because I think this PR as-is won't address the issue in the way we'd like.

**Pull request closed without merging**
